name: Export Marimo Notebooks to HTML

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  export-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Convert .py notebooks to HTML
        run: |
          total_files=0
          successful_conversions=0
          failed_conversions=0
          
          find notebooks -name "*.py" -type f | while read -r file; do
            total_files=$((total_files + 1))
            
            # TODO: Remove this skip condition later - temporarily skipping brl_sensitivity.py conversion
            if [[ "$file" == *"brl_sensitivity.py" ]]; then
              echo "⏭️  Skipping $file (temporary)"
              continue
            fi
            
            echo "🔄 Exporting $file..."
            
            # Set environment variable to prevent data directory access issues
            if MARIMO_SKIP_DATA_ACCESS=1 uv run marimo export html "$file" -o "${file%.py}.html" 2>&1; then
              echo "✅ Successfully exported $file"
              successful_conversions=$((successful_conversions + 1))
            else
              echo "❌ Failed to export $file"
              failed_conversions=$((failed_conversions + 1))
              
              # Show error details immediately
              echo "--- Error details for $file ---"
              MARIMO_SKIP_DATA_ACCESS=1 uv run marimo export html "$file" -o "${file%.py}.html" 2>&1 || true
              echo "--- End error details ---"
            fi
          done
          
          # Display conversion summary
          echo ""
          echo "=== CONVERSION SUMMARY ==="
          echo "Total files processed: $total_files"
          echo "Successful conversions: $successful_conversions"
          echo "Failed conversions: $failed_conversions"
          
          if [ $failed_conversions -gt 0 ]; then
            echo "⚠️  Some conversions failed. Check the logs above for details."
            echo "CONVERSION_FAILED=true" >> $GITHUB_ENV
            echo "FAILED_COUNT=$failed_conversions" >> $GITHUB_ENV
          else
            echo "🎉 All conversions completed successfully!"
            echo "CONVERSION_FAILED=false" >> $GITHUB_ENV
          fi

      - name: Generate index.html with Tailwind
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='en'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> index.html
          echo "  <title>Quant Notebooks</title>" >> index.html
          echo "  <script src='https://cdn.tailwindcss.com'></script>" >> index.html
          echo "</head>" >> index.html
          echo "<body class='bg-gray-50 text-gray-900 font-sans'>" >> index.html
          echo "  <div class='max-w-4xl mx-auto p-8'>" >> index.html
          echo "    <h1 class='text-3xl font-bold mb-6'>📚 Quant Notebooks</h1>" >> index.html
          
          # Process each category folder
          for folder in notebooks/*/; do
            if [ -d "$folder" ] && ls "$folder"*.html >/dev/null 2>&1; then
              folder_name=$(basename "$folder")
              # Convert underscores to spaces for display
              display_name=$(echo "$folder_name" | tr '_' ' ' | sed 's/\b\w/\u&/g')
              echo "    <h2 class='text-2xl font-semibold mt-8 mb-4 text-gray-700 border-b border-gray-300 pb-2'>$display_name</h2>" >> index.html
              echo "    <ul class='space-y-3 mb-6'>" >> index.html
              
              for file in "$folder"*.html; do
                if [ -f "$file" ]; then
                  name=$(basename "$file" .html)
                  echo "      <li>" >> index.html
                  echo "        <a href='$file' class='block p-4 bg-white rounded-xl shadow hover:bg-gray-100 transition-colors duration-200'>" >> index.html
                  echo "          <span class='font-medium text-lg text-gray-800'>$name</span><br>" >> index.html
                  echo "          <span class='text-sm text-gray-500'>$display_name</span>" >> index.html
                  echo "        </a>" >> index.html
                  echo "      </li>" >> index.html
                fi
              done
              echo "    </ul>" >> index.html
            fi
          done
          
          echo "  </div>" >> index.html
          echo "</body></html>" >> index.html


      - name: Commit and push HTML files
        if: always()  # Run even if some conversions failed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add only HTML files that were successfully created
          git add notebooks/**/*.html index.html
          
          # Create commit message based on conversion results
          if [ "$CONVERSION_FAILED" = "true" ]; then
            commit_msg="Auto-export notebooks to HTML + update index (⚠️ $FAILED_COUNT failed)"
          else
            commit_msg="Auto-export notebooks to HTML + update index (✅ all successful)"
          fi
          
          git commit -m "$commit_msg" || echo "No changes to commit"
          git push
          
          # Set workflow status based on conversion results
          if [ "$CONVERSION_FAILED" = "true" ]; then
            echo "⚠️ Workflow completed with $FAILED_COUNT failed conversions. Check the workflow logs for details."
            exit 1  # Mark workflow as failed so it shows up in GitHub notifications
          else
            echo "🎉 Workflow completed successfully - all notebooks converted!"
          fi
