name: Export Marimo Notebooks to HTML

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  export-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Convert .py notebooks to HTML
        run: |
          shopt -s globstar
          for file in notebooks/**/*.py; do
            if [ -f "$file" ]; then
              echo "Exporting $file..."
              uv run marimo export html "$file" -o "${file%.py}.html"
            fi
          done

      - name: Generate index.html with Tailwind
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='en'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> index.html
          echo "  <title>Quant Notebooks</title>" >> index.html
          echo "  <script src='https://cdn.tailwindcss.com'></script>" >> index.html
          echo "</head>" >> index.html
          echo "<body class='bg-gray-50 text-gray-900 font-sans'>" >> index.html
          echo "  <div class='max-w-4xl mx-auto p-8'>" >> index.html
          echo "    <h1 class='text-3xl font-bold mb-6'>📚 Quant Notebooks</h1>" >> index.html
          
          # Group notebooks by folder
          for folder in $(find notebooks -type d -mindepth 1 | sort); do
            # Check if folder contains any HTML files
            if ls "$folder"/*.html 1> /dev/null 2>&1; then
              folder_name=$(basename "$folder")
              echo "    <h2 class='text-2xl font-semibold mt-8 mb-4 text-gray-700 border-b border-gray-300 pb-2'>$folder_name</h2>" >> index.html
              echo "    <ul class='space-y-3 mb-6'>" >> index.html
              
              # Process HTML files in this folder
              for file in "$folder"/*.html; do
                if [ -f "$file" ]; then
                  # Properly encode the URL (replace spaces with %20)
                  encoded_url=$(echo "$file" | sed 's/ /%20/g')
                  name=$(basename "$file" .html)
                  echo "      <li>" >> index.html
                  echo "        <a href='$encoded_url' class='block p-4 bg-white rounded-xl shadow hover:bg-gray-100 transition-colors duration-200'>" >> index.html
                  echo "          <span class='font-medium text-lg text-gray-800'>$name</span><br>" >> index.html
                  echo "          <span class='text-sm text-gray-500'>$folder_name</span>" >> index.html
                  echo "        </a>" >> index.html
                  echo "      </li>" >> index.html
                fi
              done
              echo "    </ul>" >> index.html
            fi
          done
          
          echo "  </div>" >> index.html
          echo "</body></html>" >> index.html


      - name: Commit and push HTML files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add notebooks/**/*.html index.html
          git commit -m "Auto-export notebooks to HTML + update index" || echo "No changes to commit"
          git push
